import React, { useState, useRef, useEffect } from 'react';
import { ChatMessage } from '../../types';
import { sendToGemini } from '../../services/geminiService';

export const Terminal: React.FC = () => {
  const [input, setInput] = useState('');
  const [history, setHistory] = useState<ChatMessage[]>([
    { role: 'model', text: 'WEBFABRIK MAINFRAME ONLINE. AWAITING INPUT...', timestamp: Date.now() }
  ]);
  const [isLoading, setIsLoading] = useState(false);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [history]);

  const handleCommand = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMsg: ChatMessage = { role: 'user', text: input, timestamp: Date.now() };
    setHistory(prev => [...prev, userMsg]);
    setInput('');
    setIsLoading(true);

    const responseText = await sendToGemini(input);
    
    const modelMsg: ChatMessage = { role: 'model', text: responseText, timestamp: Date.now() };
    setHistory(prev => [...prev, modelMsg]);
    setIsLoading(false);
  };

  return (
    <div className="max-w-4xl mx-auto">
      <div className="mb-4 border-l-4 border-neon-green pl-4">
        <h2 className="text-3xl font-display text-neon-green">AI_TERMINAL_ACCESS</h2>
        <p className="text-xs text-neon-blue/60">DIRECT UPLINK TO GEMINI-2.5-FLASH NODE</p>
      </div>

      <div className="bg-black border border-neon-green/50 rounded-lg p-1 shadow-[0_0_20px_rgba(57,255,20,0.15)]">
        <div className="bg-retro-black/90 p-4 h-[500px] overflow-y-auto font-mono text-sm md:text-base scrollbar-hide">
          {history.map((msg, idx) => (
            <div key={idx} className={`mb-4 ${msg.role === 'user' ? 'text-right' : 'text-left'}`}>
              <span className={`inline-block px-2 py-1 ${msg.role === 'user' ? 'text-neon-pink' : 'text-neon-green'}`}>
                {msg.role === 'user' ? '> USER:' : '> SYSTEM:'}
              </span>
              <div className={`inline-block p-2 rounded border ${
                msg.role === 'user' 
                  ? 'border-neon-pink/30 bg-neon-pink/5 text-neon-pink' 
                  : 'border-neon-green/30 bg-neon-green/5 text-neon-green'
              } max-w-[80%] whitespace-pre-wrap`}>
                {msg.text}
              </div>
            </div>
          ))}
          {isLoading && (
            <div className="text-neon-green animate-pulse">
              > SYSTEM: PROCESSING_DATA...
            </div>
          )}
          <div ref={bottomRef} />
        </div>

        <form onSubmit={handleCommand} className="border-t border-neon-green/30 p-2 flex bg-black">
          <span className="text-neon-green mr-2 py-2">{'>'}</span>
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="ENTER COMMAND OR QUERY..."
            className="flex-grow bg-transparent border-none outline-none text-neon-green placeholder-neon-green/30 font-mono"
            autoFocus
          />
          <button 
            type="submit"
            disabled={isLoading}
            className="px-4 py-1 bg-neon-green/20 text-neon-green border border-neon-green/50 hover:bg-neon-green hover:text-black transition-colors disabled:opacity-50"
          >
            SEND
          </button>
        </form>
      </div>
      
      <div className="mt-2 text-xs text-center text-gray-600">
        * ACCESSING NEURAL NET. RESPONSES GENERATED BY AI.
      </div>
    </div>
  );
};