import React, { useState, useRef, useEffect } from 'react';
import { ChatMessage } from '../../types';
import { sendToGemini } from '../../services/geminiService';

export const Terminal: React.FC = () => {
  const [input, setInput] = useState('');
  const [history, setHistory] = useState<ChatMessage[]>([
    { 
      role: 'model', 
      text: `VANDENENDE.IT MAINFRAME ONLINE v2.5.
----------------------------------------
ACCESSING PERSONNEL DATABASE: MAARTEN VAN DEN ENDE.
I can answer questions about Maarten's freelance projects, technical stack, or career history at Xebia, ING, and more.

TRY ASKING:
> "What was his role at Xebia?"
> "Tell me about the Lely project."
> "What AWS certifications does he have?"
----------------------------------------
AWAITING INPUT...`, 
      timestamp: Date.now() 
    }
  ]);
  const [isLoading, setIsLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTo({
        top: scrollRef.current.scrollHeight,
        behavior: 'smooth'
      });
    }
  }, [history]);

  const handleCommand = async (e: React.FormEvent, overrideInput?: string) => {
    if (e) e.preventDefault();
    const cmd = overrideInput || input;
    
    if (!cmd.trim() || isLoading) return;

    const userMsg: ChatMessage = { role: 'user', text: cmd, timestamp: Date.now() };
    setHistory(prev => [...prev, userMsg]);
    setInput('');
    setIsLoading(true);

    const responseText = await sendToGemini(cmd);
    
    const modelMsg: ChatMessage = { role: 'model', text: responseText, timestamp: Date.now() };
    setHistory(prev => [...prev, modelMsg]);
    setIsLoading(false);
  };

  const quickCommands = [
    "Who is Maarten?",
    "Tell me about the Freelance era",
    "What is his tech stack?",
    "Detail the Xebia years"
  ];

  return (
    <div className="max-w-4xl mx-auto">
      <div className="mb-4 border-l-4 border-neon-green pl-4">
        <h2 className="text-3xl font-display text-neon-green">AI_TERMINAL_ACCESS</h2>
        <p className="text-xs text-neon-blue/60">INTERACTIVE PROFILE DATABASE. POWERED BY GEMINI AI.</p>
      </div>

      <div className="bg-black border border-neon-green/50 rounded-lg p-1 shadow-[0_0_20px_rgba(57,255,20,0.15)]">
        <div 
          ref={scrollRef}
          className="bg-retro-black/90 p-4 h-[500px] overflow-y-auto font-mono text-sm md:text-base scrollbar-hide"
        >
          {history.map((msg, idx) => (
            <div key={idx} className={`mb-4 ${msg.role === 'user' ? 'text-right' : 'text-left'}`}>
              <span className={`inline-block px-2 py-1 ${msg.role === 'user' ? 'text-neon-pink' : 'text-neon-green'}`}>
                {msg.role === 'user' ? '> USER:' : '> SYSTEM:'}
              </span>
              <div className={`inline-block p-2 rounded border ${
                msg.role === 'user' 
                  ? 'border-neon-pink/30 bg-neon-pink/5 text-neon-pink' 
                  : 'border-neon-green/30 bg-neon-green/5 text-neon-green'
              } max-w-[85%] whitespace-pre-wrap`}>
                {msg.text}
              </div>
            </div>
          ))}
          {isLoading && (
            <div className="text-neon-green animate-pulse">
              {'> SYSTEM: PROCESSING_DATA...'}
            </div>
          )}
        </div>

        <form onSubmit={handleCommand} className="border-t border-neon-green/30 p-2 flex bg-black">
          <span className="text-neon-green mr-2 py-2">{'>'}</span>
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="ENTER COMMAND OR QUERY..."
            className="flex-grow bg-transparent border-none outline-none text-neon-green placeholder-neon-green/30 font-mono"
            autoFocus
          />
          <button 
            type="submit"
            disabled={isLoading}
            className="px-4 py-1 bg-neon-green/20 text-neon-green border border-neon-green/50 hover:bg-neon-green hover:text-black transition-colors disabled:opacity-50"
          >
            EXECUTE
          </button>
        </form>
      </div>

      {/* Quick Commands */}
      <div className="mt-4 flex flex-wrap gap-2 justify-center">
        {quickCommands.map((cmd, idx) => (
          <button
            key={idx}
            onClick={(e) => handleCommand(e, cmd)}
            disabled={isLoading}
            className="text-xs font-mono px-3 py-2 border border-neon-blue/30 text-neon-blue hover:bg-neon-blue hover:text-black transition-all disabled:opacity-30"
          >
            [{cmd}]
          </button>
        ))}
      </div>
      
      <div className="mt-2 text-[10px] text-center text-gray-600">
        * ACCESSING NEURAL NET. RESPONSES GENERATED BY AI.
      </div>
    </div>
  );
};